### ISSUE TITLE
wrong ownership of /etc/openvpn/keys/

### ISSUE THREAD

**Issue by roumano** [sansible/openvpn#15]
Actually it's harcoded the ownership (root) & user permission of /etc/openvpn/keys/ via : 

```
- name: Create OpenVPN keys directory
  become: yes 
  file:
    path: "{{ openvpn.keydir }}"
    state: directory
    owner: root
    group: root
    mode: 0600
```
But the ownership of file on it are not specify : 

```
- name: Download OpenVPN server keys
  become: yes 
  command: "aws s3 cp --region {{ openvpn.aws_s3_region }} {{ openvpn.aws_s3_options }} {{ openvpn.aws_s3_path }}/{{ item }} {{ openvpn.keydir }}"
  args:
    creates: "{{ openvpn.keydir }}/{{ item }}"
  with_items:
    - ca.crt
    - "dh{{ openvpn.key_size }}.pem"
    - server.crt
    - server.key
```

and the default user of openvpn ( nobody ) can't access to them : 
```
grep user defaults/main.yml 
  user: nobody
```
my openvpn log : 

```
Options error: --dh fails with '/etc/openvpn/keys/dh2048.pem': Permission denied
Options error: --ca fails with '/etc/openvpn/keys/ca.crt': Permission denied
Options error: --cert fails with '/etc/openvpn/keys/server.crt': Permission denied
Options error: --key fails with '/etc/openvpn/keys/server.key': Permission denied
Options error: --status fails with 'openvpn-status.log': Permission denied
```

For me 2 things need to be done : 
* Update the Create OpenVPN keys directory to use the user specified on the configuration ( install.yml )
* Add a task to change recursively the owner of file under '/etc/openvpn/keys/ ( in configure.yml after downloading file (done via aws s3 cp  )
